//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquashNext.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Buildings = new HashSet<Building>();
            this.Users = new HashSet<User>();
        }
    
        public int organizationId { get; set; }
        public string orgName { get; set; }
        public string orgAddress { get; set; }
        public string orgCity { get; set; }
        public string orgPhoneNumber { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
