//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquashNext.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Province
    {
        public Province()
        {
            this.Users = new HashSet<User>();
        }
    
        [Display(Name = "Province ID")]
        public string provinceId { get; set; }

        [Display(Name = "Province Name")]
        public string provinceName { get; set; }

        [Display(Name = "Country ID")]
        public int countryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
