//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquashNext.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TournamentRule
    {
        [Display(Name = "Tournament Rules")]
        public int tournamentRuleId { get; set; }

        [Display(Name = "Placeholder")]
        public string placeholder { get; set; }
    }
}
