//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalSquashNext.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserLadder
    {
        [Display(Name = "Position")]
        public int position { get; set; }

        [Display(Name = "User ID")]
        public int userId { get; set; }

        [Display(Name = "Ladder ID")]
        public int ladderId { get; set; }
    
        public virtual Ladder Ladder { get; set; }
        public virtual User User { get; set; }
    }
}
